### ISSUE TITLE
🐛 [HOSTED] Generated Issue: TypeError

### ISSUE THREAD

**Issue by N-Pu** [jikan-me/jikan-rest#438] opened 2023-09-29 10:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```TypeError```
Status code: ```0```
Message: ```App\Anime::adaptBroadcastValue(): Argument #1 ($broadcast) must be of type array|string|null, MongoDB\Model\BSONDocument given, called in /var/www/jikan-rest/app/Anime.php on line 121```
Trace: ```/var/www/jikan-rest/app/Anime.php on line 406```

--> GET https://api.jikan.moe/v4/random/anime
--> END GET
<-- 500 Internal Server Error https://api.jikan.moe/v4/random/anime (211ms)

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/random/anime

**Comment by irfan-dahir** [comment] 2023-10-20 14:49
I can't reproduce this anymore. Closing for now. Feel free to re-open it if it occurs again.

**Closed by irfan-dahir** 2023-10-20 14:49 UTC
Labels: bug, needs triage
