### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by v-sudo29** [jikan-me/jikan-rest#394] opened 2023-06-11 22:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The endpoint to get top upcoming anime is giving me an empty array. 

I've tested other endpoints and they seem to be working fine.

### Expected Behavior

I expected to get the first 25 results for top upcoming anime.

### Steps To Reproduce

https://api.jikan.moe/v4/top/anime?filter=upcoming

### Environment

```markdown
- OS: Mac 11.2.3
- Browser: Brave 1.47.186
- plain hosting
```

**Comment by irfan-dahir** [comment] 2023-06-11 22:33
Thanks for reporting. This is a duplicate of https://github.com/jikan-me/jikan-rest/issues/388 so I'll close this one. You can follow track the issue there.

**Closed by irfan-dahir** 2023-06-11 22:33 UTC
Labels: bug, needs triage
