### ISSUE TITLE
🐛 Jikan returns 404 for some recently added anime

### ISSUE THREAD

**Issue by YoshiWalsh** [jikan-me/jikan-rest#378] opened 2023-05-17 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For anime that's been very recently added to MAL, Jikan returns a 404 error. The response body for `https://api.jikan.moe/v4/anime/55312/full` says:

```json
{
    "status": 404,
    "type": "BadResponseException",
    "message": "Resource does not exist",
    "error": "404 on https://myanimelist.net/anime/55312/"
}
```

But accessing https://myanimelist.net/anime/55312/ works, it returns 200. Strangely, show 55315 was added more recently and does not return 404. Until recently I was also getting this issue for anime 55302.

This is a bit of a problem because users can add the show to their animelist, but I can't retrieve any details about it. 

### Expected Behavior

Since the anime exists, Jikan should return 200 with the details.

### Steps To Reproduce

Look at the recently added anime list: https://myanimelist.net/anime.php?o=9&c%5B0%5D=a&c%5B1%5D=d&cv=2&w=1

Try requesting details about recently added anime. Hopefully one of them allows you to repro the issue.

### Environment

```markdown
- OS: Windows 10, Amazon Linux 2 (Lambda)
- Browser: Postman, Marika
```

### Anything else?

Is Jikan caching 404 errors to avoid unnecessary upstream requests?

How is Jikan getting a 404 error to cache in the first place? Are there circumstances were MAL will return 404 even though an anime already exists? (E.g. pending anime?)

Are there users of Jikan polling non-existent show IDs in order to find the newest added shows?

**Comment by pushrbx** [comment] 2023-05-18 17:09
> How is Jikan getting a 404 error to cache in the first place? Are there circumstances were MAL will return 404 even though an anime already exists? (E.g. pending anime?)

It is recommended to sanity check with: https://dbsentinel.sean.fish/
In case of MAL whenever an entry requested to be added (by a user), it gets an ID and is listed "on the website" - unlisted; at this point no one can add it to their list. If its approved it keeps that ID, else it becomes a 404. There can be also a use case where the moderators first unapprove an added entry, becomes 404, then approve it again. Jikan only updates itself daily, or if you directly request the ID again. When you directly ask for the ID, e.g. `https://api.jikan.moe/v4/anime/55312/full` then jikan check the cache, if empty, then sends a request to upstream. If upstream returns an error, then Jikan returns `404` response. `404` responses are not cached.

**Comment by pushrbx** [comment] 2023-05-19 08:15
@irfan-dahir One preventative change I can think of to partially resolve this issue is to update the error message to be more informative as we can't do too much about the upstream responses.
Something along the lines of 
```
Cache has expired or it was stale for the requested item. 
Tried to retrieve an update, but the upstream server has responded with a not successful status code. 
Please try again later.
```

**Comment by irfan-dahir** [comment] 2023-10-20 15:05
This should be resolved now since we only return approved entries now by default. I can't reproduce it anymore either. We're also running sanity by removing deleted entries on a daily basis via [mal-id-cache](https://github.com/seanbreckenridge/mal-id-cache)

Let me know if it still persists though, otherwise, I think we can go ahead and close this issue.

@JoshuaWalsh cc: @pushrbx

**Comment by irfan-dahir** [comment] 2023-10-26 08:56
Unfortunately, I was able to reproduce this recently. However in a slightly different manner. 
Recently added entries initially show up as 404 but if I re-request it, it will show the appropriate response.

This is definitely a caching issue. I need to figure out where. Leaving the ticket open until then.

**Comment by irfan-dahir** [comment] 2023-10-28 09:27
Updating caching on multiple levels. 404 is now only cached for 1 hour. Turned off proxy_cache_revalidate and proxy cache background updates on nginx - _I think_ they were causing the issue as well. But let's see 🤞

**Comment by irfan-dahir** [comment] 2024-09-20 22:20
Spring cleaning 🧹: Closing as it was seemingly resolved + the introduction of the `unapproved` flag automatically filters out anime that were the main cause of this issue.

**Closed by irfan-dahir** 2024-09-20 22:20 UTC
Labels: bug, needs triage
