### ISSUE TITLE
Incorrect indexing for paginated elements

### ISSUE THREAD

**Issue by nerg4l** [jikan-me/jikan-rest#352] opened 2023-02-12 20:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Elements in paginated response wrapped in object because indexing of elements starts from offset in the paginated response.

See: https://jikan.hunsubdb.moe/v4/anime?q=one&page=3

### Expected Behavior

Elements in paginated response should be wrapped in an array `[]`.

See: https://jikan.hunsubdb.moe/v4/anime?q=one&page=1

### Steps To Reproduce

1. Open https://jikan.hunsubdb.moe/v4/anime?q=one&page=3
2. Check the index of the first element

### Environment

```markdown
- Browser: Firefox 109.0.1

- Client: Guzzle
```

**Comment by pushrbx** [comment] 2023-02-13 00:31
Duplicate of #298 .
Fixed in #346

**Comment by pushrbx** [comment] 2023-06-02 21:29
Fixed in https://github.com/jikan-me/jikan-rest/pull/346

**Closed by pushrbx** 2023-06-02 21:29 UTC
Labels: bug, duplicate
