### ISSUE TITLE
🐛 [HOSTED] Generated Issue: ObjectNotFound

### ISSUE THREAD

**Issue by itsTKRaz** [jikan-me/jikan-rest#476] opened 2024-01-22 23:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```Typesense\Exceptions\ObjectNotFound```
Status code: ```0```
Message: ```Could not find a field named `popularity` in the schema for sorting.```
Trace: ```/var/www/vendor/typesense/typesense-php/src/ApiCall.php on line 348```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime?q=Naruto&page=1

### Environment

```markdown
Server OS: Latest Debian LTS
PHP Version: 8.2.6
Caching: "database"
Scout and Typesense are enable
```

### Anything else?

N/A

**Comment by pushrbx** [comment] 2024-01-23 14:28
duplicate of #477  same thing applies what I said  there

**Closed by pushrbx** 2024-01-23 14:28 UTC
Labels: bug, needs triage
