### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by ShaneIsrael** [jikan-me/jikan-rest#90] opened 2020-02-16 18:14 UTC
Noticed I was getting this occasionally this morning. Am unable to investigate it further right now but will try to later.

`Return value of Jikan\\Parser\\Anime\\AnimeParser::getScoredBy() must be of the type int or null, string returned`

```json
{
  "status": 500,
  "type": "Exception",
  "message": "Unhandled Exception. Please follow report_url to generate an issue on GitHub",
  "trace": "/var/www/html/vendor/jikan-me/jikan/src/Parser/Anime/AnimeParser.php at line 428",
  "error": "Return value of Jikan\\Parser\\Anime\\AnimeParser::getScoredBy() must be of the type int or null, string returned",
  "report_url": null
}
```

**Comment by GSculerlor** [comment] 2020-02-16 18:21
Duplicate of https://github.com/jikan-me/jikan/issues/268

**Comment by irfan-dahir** [comment] 2020-02-16 18:47
Should be fixed now. Just pushed the update to the servers. 

Closing the issue. Please re-open it if it still persists for you including the request that's being made, thanks!

**Closed by irfan-dahir** 2020-02-16 18:47 UTC
