### ISSUE TITLE
V4 vs. V3 season API different number of anime returned

### ISSUE THREAD

**Issue by koji98** [jikan-me/jikan-rest#256] opened 2022-07-07 14:23 UTC
I realized that the V3 api returns a lot more anime in a season than V4. I believe it's because V4 season API only returns new anime of a season, whereas the V3 returns new and continuing anime airing in that particular season. Is this the case? Are there any other differences developers should be aware of?

**Comment by irfan-dahir** [comment] 2022-07-07 14:25
Hey, this is a known issue. v4 returns only TV entries where-as v3 returns whatever MAL returns which is all the other types too (OVA, Movie, etc).

We're currently figuring this out. I'll close this as it's a duplicate of #217 Please follow the issue there

**Closed as not planned by irfan-dahir** 2022-07-07 14:25 UTC
