### ISSUE TITLE
[OFFICIAL] Generated Issue: ConnectionTimeoutException

### ISSUE THREAD

**Issue by timothee-durand** [jikan-me/jikan-rest#312] opened 2022-11-29 13:50 UTC
Please fill out the details below.

**Summary:**
The api send back a 500 error code

**Steps to reproduce:**
Get https://api.jikan.moe/v4/anime

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```MongoDB\Driver\Exception\ConnectionTimeoutException```
**Code:** ```13053```
**Message:** ```No servers yet eligible for rescan```
**Trace:** ```/var/www/jikan-rest/vendor/mongodb/mongodb/src/functions.php on line 487```
**Request:** `GET /v4/anime`

**Comment by pushrbx** [comment] 2022-11-29 14:27
duplicate of #311 
we will track the issue there

**Closed by pushrbx** 2022-11-29 14:27 UTC
Labels: duplicate
