### ISSUE TITLE
Upcoming Anime API request returning no animes.🐛 

### ISSUE THREAD

**Issue by ahmedalashhab** [jikan-me/jikan-rest#402] opened 2023-06-18 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![CleanShot 2023-06-18 at 13 37 25@2x](https://github.com/jikan-me/jikan-rest/assets/96653465/bd7c4e81-45fc-4b17-83ec-1b46234f6c96)

When requesting upcoming animes from the Jikan API I am receiving an empty response as the above screenshot shows.

### Expected Behavior

An array of upcoming animes.

### Steps To Reproduce

GET /v4/top/anime?filter=upcoming

This request retrieves an empty array of episodes.

### Environment

```markdown
Used Public API using Chrome Version 114.0.5735.133 (Official Build) (arm64)
```

**Comment by irfan-dahir** [comment] 2023-06-18 17:28
This is a duplicate of https://github.com/jikan-me/jikan-rest/issues/388 so I'll close this one. You can follow track the issue there.

**Closed by irfan-dahir** 2023-06-18 17:28 UTC
Labels: bug, needs triage

**Comment by sachinsoumya** [comment] 2023-06-22 05:52
Hello all . Today I am also facing the same issue on filter query parameter like https://api.jikan.moe/v4/top/anime , so if I want to add filter query parameter on upcoming like ttps://api.jikan.moe/v4/top/anime?filter=upcoming ,then it is giving error and the data is not coming . This one was not coming before , but now it is showing 
![Screenshot (162)](https://github.com/jikan-me/jikan-rest/assets/80940744/53eb5350-e6b4-421b-ad1b-fe7ff4e57a2f)
error like this. Please explain me how to fix or what is happening ,please explain .
