### ISSUE TITLE
Top Upcoming anime list not being retrieved

### ISSUE THREAD

**Issue by ralvinc** [jikan-me/jikan-rest#415] opened 2023-06-29 12:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Request I tried:

https://api.jikan.moe/v4/top/anime?filter=upcoming&limit=5

returns:
{"pagination":{"last_visible_page":1,"has_next_page":false,"current_page":1,"items":{"count":0,"total":0,"per_page":5}},"data":[]}

### Expected Behavior

Expected return:

a list of top upcoming anime

### Environment

```markdown
Browser: Microsoft Edge Version 109.0.1518.100
```

**Comment by pushrbx** [comment] 2023-06-30 12:09
duplicate of #388 
fixed in: #408  -> not yet deployed

**Comment by irfan-dahir** [comment] 2023-07-09 16:25
Resolved

**Closed by irfan-dahir** 2023-07-09 16:25 UTC
Labels: bug, duplicate
