### ISSUE TITLE
🐛 Hello all . Today I am also facing the same issue on filter query parameter like https://api.jikan.moe/v4/top/anime , so if I want to add filter query parameter on upcoming like ttps://api.jikan.moe/v4/top/anime?filter=upcoming ,then it is giving error and the data is not coming . This one was not coming before , but now it is showing error like this, Please explain me how to fix or what is happening ,please explain .

### ISSUE THREAD

**Issue by sachinsoumya** [jikan-me/jikan-rest#405] opened 2023-06-22 06:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My current behavior is data is not coming , showing error when I add upcoming filter on https://api.jikan.moe/v4/top/anime like this https://api.jikan.moe/v4/top/anime?limit=18&filter=upcoming .This was not coming previously , but recently it is showing like this.
![Screenshot (162)](https://github.com/jikan-me/jikan-rest/assets/80940744/751a8569-9df2-4d03-9e59-7703fc27bc9e)

### Expected Behavior

My expected behavior is data should come , when I add upcoming filter query parameters like https://api.jikan.moe/v4/top/anime?limit=18&filter=upcoming , same like when we add other query parameters . 

### Steps To Reproduce

https://api.jikan.moe/v4/top/anime?limit=18&filter=upcoming
![Screenshot (162)](https://github.com/jikan-me/jikan-rest/assets/80940744/5f4f1846-e31d-4bd6-9dc0-280fb9482eb9)

### Environment

```markdown
OS: Window 11
Browser: Chrome  114.0.5735.134
```

### Anything else?

![Screenshot (162)](https://github.com/jikan-me/jikan-rest/assets/80940744/fd1daa07-770a-44d9-bcc6-09b2d0e8a8d3)

**Comment by irfan-dahir** [comment] 2023-06-22 08:14
Hi, this is a duplicate of https://github.com/jikan-me/jikan-rest/issues/388 so I'll close this one. You can track the issue there, thanks.

**Closed by irfan-dahir** 2023-06-22 08:14 UTC
Labels: bug, needs triage
