### ISSUE TITLE
Api return badresponse with 200 Code

### ISSUE THREAD

**Issue by Kamil-Malik** [jikan-me/jikan-rest#339] opened 2023-01-25 11:42 UTC
So, apparently when the API returning badresponse, the code is still 200. And, in this scenario my android app cannot reload the data as the http request is considered to be a valid request and therefore to be cached in local data.
![api_error](https://user-images.githubusercontent.com/85838849/214554687-d6c3cfa2-7a4c-4876-af95-7eb9f88123e0.jpg)

**Comment by pushrbx** [comment] 2023-01-25 19:28
duplicate of #314

**Comment by pushrbx** [comment] 2023-01-25 20:01
Another thought on this: there might be a situation where the android runtime don't recognise the `408` http status code.

**Comment by irfan-dahir** [comment] 2023-07-22 15:20
Should be resolved now. Feel free to re-open if it occurs again.

**Closed by irfan-dahir** 2023-07-22 15:20 UTC
Labels: bug
