### ISSUE TITLE
API returning same genres multiple times

### ISSUE THREAD

**Issue by GMkonan** [jikan-me/jikan-rest#205] opened 2022-03-23 19:27 UTC
Sorry if this is the wrong place to post this. But I was trying to use the `getAnimeGenres` in Jikan v4 but the result I'm getting always contain multiple equal genres. Check out screenshot from response of the endpoint `https://api.jikan.moe/v4/genres/anime`:
![image](https://user-images.githubusercontent.com/42452771/159779306-a65b6fab-1184-49c7-b3cd-f333ef1be52b.png)
I've only put this in a json formatter, this is the raw response I'm getting.

As a simple workaround I've just filtered the list of genres by id, but I thought I should create a issue since I didn't find anyone that reported this. Sorry if this is something you guys already knew.

Thanks for the amazing project!

**Comment by luiderek** [comment] 2022-04-19 17:56
Yeah I just encountered this myself, I think for genres action is always listed 4 times as well.

**Comment by nerg4l** [comment] 2022-06-07 20:05
I can see the official Jikan API displays duplicates (146 items) but if I try to reproduce it locally then there are no duplicates (75 elements). I could only find `indexer:genres` artisan command which populates genres table ()and run it multiple times without a problem). Is there any other commands/methods I might missed?

**Comment by irfan-dahir** [comment] 2022-06-07 20:09
@nerg4l I'm unsure why this is happening as well over time as well as I couldn't replicate it locally.
`indexer:genres` is added as a daily [cron task here](https://github.com/jikan-me/jikan-rest/blob/5a7fcfeced0c113be27aea0e1a09889f813df1d7/app/Console/Kernel.php#L61)

**Comment by GMkonan** [comment] 2022-06-07 20:30
From what I've seem it's not just `data` coming with two objects that are equal, the same object can be 4 to 2 times in the same list, and it seems like it's always the same genres that appear the same amount of times every request. So **Actions** appears 4 times, **Romance** appears 3 times, **Boys Love** 2 times and so on.

Obs: **None** of this observations were done locally as well

**Comment by irfan-dahir** [comment] 2022-06-07 20:36
I've wiped the collection and rebuilt it. Let's monitor it from here.

**Comment by GMkonan** [comment] 2022-06-26 10:39
any news here?

**Comment by nerg4l** [comment] 2022-06-26 12:22
So far there are no duplicates. The API lists the same 76 genres since it was wiped.

**Comment by GMkonan** [comment] 2022-06-26 12:26
Okay! I just wanted to know if anyone had anything more to say about it, because for me it seems like everything was solved so we can already close this issue.

**Comment by irfan-dahir** [comment] 2022-06-26 15:03
Closing. Feel free to re open if it occurs again

**Closed by irfan-dahir** 2022-06-26 15:03 UTC
Labels: bug
