### ISSUE TITLE
🐛 Request schedules same response for every request different Filter (days of week)

### ISSUE THREAD

**Issue by Artimael** [jikan-me/jikan-rest#416] opened 2023-07-03 18:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue is relationated to issue 406: https://github.com/jikan-me/jikan-rest/issues/406

i use the API Jikan in my discord server and I noticed this request https://api.jikan.moe/v4/schedules?filter=monday still get the same answer for every param i put

The problem still continue 

![image](https://github.com/jikan-me/jikan-rest/assets/9206105/b3a29046-6757-4d03-8ee9-f7c3af3829da)

### Expected Behavior

I expect when i use the service i get the list of anime by day

### Steps To Reproduce

Use Postman and copy the url https://api.jikan.moe/v4/schedules?filter=monday

Then execute the service and see

Change the param monday for tuesday or any day and see its same

### Environment

```markdown
- OS: Windows 10
- Postman
```

### Anything else?

And i notice this because i use the api in my discord server and its every day say the same

**Comment by pushrbx** [comment] 2023-07-08 16:17
duplicate of #406
fixed in #408
not yet deployed

**Comment by irfan-dahir** [comment] 2023-07-09 16:26
@pushrbx Resolved as  https://api.jikan.moe/v4/schedules/monday but we need BC for  https://api.jikan.moe/v4/schedules?filter=monday

**Closed** 2023-07-21 16:09 UTC
Labels: bug, duplicate
