### ISSUE TITLE
[OFFICIAL] Generated Issue: Error

### ISSUE THREAD

**Issue by GittyCyber22** [jikan-me/jikan-rest#376] opened 2023-05-05 13:58 UTC
Please fill out the details below.

**Summary:** Yes its me again, I just want to ask how to overcome my status: 500 error. Is it my fault? if it is, can you show me how to solve this error because I already read the documentary and I don't understand what and where do I request it incorrectly. I requesting to https://api.jikan.moe/v4/top/reviews to get anime reviews. 

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.5@6be2fa68bacf7abe7c51d5a0633ffc218aea078b```
**PHP:** ```8.1.18```
**Redis**: ```Connected```
**Exception:** ```Error```
**Code:** ```0```
**Message:** ```Call to undefined method Jikan\MyAnimeList\MalClient::getRecentReviews()```
**Trace:** ```/var/www/jikan-rest/app/Http/Controllers/V4DB/TopController.php on line 390```
**Request:** `GET /v4/top/reviews?limit=2000&page=1`

**Comment by irfan-dahir** [comment] 2023-05-05 18:23
Hope that explains ^

I'm closing this issue as it's a duplicate of #344

**Closed by irfan-dahir** 2023-05-05 18:23 UTC
