### ISSUE TITLE
[OFFICIAL] Generated Issue: ObjectNotFound

### ISSUE THREAD

**Issue by dev-dhams** [jikan-me/jikan-rest#296] opened 2022-11-27 17:25 UTC
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```Typesense\Exceptions\ObjectNotFound```
**Code:** ```0```
**Message:** ```Could not find a field named `name` in the schema.```
**Trace:** ```/var/www/jikan-rest/vendor/typesense/typesense-php/src/ApiCall.php on line 348```
**Request:** `GET /v4/characters?page=0&limit=15&q=saki&order_by=favorites&sort=desc`

**Comment by pushrbx** [comment] 2022-11-27 21:34
@irfan-dahir the indexing job needs to be ran again, and if that doesn't fix it, then the collection in typesense needs to be dropped and created again with artisan + scout command.

**Comment by dharmeshphd** [comment] 2022-11-28 13:05
It still not resolving the issue.

**Comment by pushrbx** [comment] 2022-11-28 19:25
This should be working now. Let us know if it's still broken. We are tracking the root cause issue in #304

**Closed by pushrbx** 2022-11-28 19:25 UTC
Labels: bug
