### ISSUE TITLE
Episodes has_next_page is incorrect

### ISSUE THREAD

**Issue by Fribb** [jikan-me/jikan-rest#353] opened 2023-03-10 15:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I request the episodes of an anime which only has one page of episodes the "has_next_page" is set to true.

Example: https://api.jikan.moe/v4/anime/30806/episodes

```
  "pagination": {
    "last_visible_page": 1,
    "has_next_page": true
  },
```

But there are only 12 Episodes (which is also the total number of episodes)

Same behaviour on https://api.jikan.moe/v4/anime/30806/episodes?page=1

But when I request the second page https://api.jikan.moe/v4/anime/30806/episodes?page=2 it is correctly set to false

### Expected Behavior

has_next_page should be set to false if there is no next page

### Steps To Reproduce

1. Open https://api.jikan.moe/v4/anime/30806/episodes?page=1 and has_next_page is set to true
2. open https://api.jikan.moe/v4/anime/30806/episodes?page=2 and it is empty with has_next_page set to false

### Environment

```markdown
- OS: Windows 10
- Browser: Firefox 110.0.1 (64-Bit), Chrome 110.0.5481.180 (Official Build) (64-bit)
```

**Comment by pushrbx** [comment] 2023-03-10 19:25
Please search for issues next time, this is a duplicate of https://github.com/jikan-me/jikan-rest/issues/329 and https://github.com/jikan-me/jikan/issues/501

It will be fixed in next release #346

**Closed by pushrbx** 2023-03-10 19:25 UTC
Labels: bug, duplicate

**Comment by Fribb** [comment] 2023-03-10 19:36
I actually did search for an already existing issue in regards to this but I searched for has_next_page which only resulted in 3 issues unrelated to this from what I could see.

Regardless, thanks for the info.

Any ETA on when this will be on the public API?

**Comment by pushrbx** [comment] 2023-03-12 23:57
> Any ETA on when this will be on the public API?
No idea. Irfan is AWOL.
