### ISSUE TITLE
🐛 [OFFICIAL] Generated Issue: ErrorException

### ISSUE THREAD

**Issue by IsraelGomes** [jikan-me/jikan-rest#463] opened 2023-12-17 13:48 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```ErrorException```
Status code: ```0```
Message: ```Undefined array key "characters"```
Trace: ```/var/www/jikan-rest/vendor/illuminate/collections/Collection.php on line 1734```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/manga/102286/characters

### Anything else?

Here is the raw response when returned to my browser:
{"status":500,"type":"Exception","message":"Unhandled Exception. Please follow report_url to generate an issue on GitHub","trace":"\/var\/www\/jikan-rest\/vendor\/illuminate\/collections\/Collection.php at line 1734","error":"Undefined array key \"characters\"","report_url":"https:\/\/github.com\/jikan-me\/jikan-rest\/issues\/new?template=bug.yml&title=%F0%9F%90%9B+%5BOFFICIAL%5D+Generated+Issue%3A+ErrorException&system_env=Jikan+Parser+Version%2A%2A%3A+%60%60%60v4.0.8%40db7c2d2e940c028ba3bdfac71d66e39daf74952a%60%60%60%0APHP%3A+%60%60%608.1.20%60%60%60%0AIs+redis+used%3A+%60%60%60Connected%60%60%60&repro_steps=Http+Request%3A+%60GET+%2Fv4%2Fmanga%2F102286%2Fcharacters&expected_behavior=The+API+should+have+returned+a+successful+response+with+data.&current_behavior=The+API+has+returned+an+error%3A+%0A%60%60%60ErrorException%60%60%60%0AStatus+code%3A+%60%60%600%60%60%60%0AMessage%3A+%60%60%60Undefined+array+key+%22characters%22%60%60%60%0ATrace%3A+%60%60%60%2Fvar%2Fwww%2Fjikan-rest%2Fvendor%2Filluminate%2Fcollections%2FCollection.php+on+line+1734%60%60%60"}

and the raw url I used: https://api.jikan.moe/v4/manga/102286/characters

**Comment by pushrbx** [comment] 2023-12-17 22:51
duplicate of #460

**Closed** 2023-12-20 15:19 UTC
Labels: bug, duplicate, needs triage
