### ISSUE TITLE
[OFFICIAL] Generated Issue: Error

### ISSUE THREAD

**Issue by NuggetMcPollo** [jikan-me/jikan-rest#349] opened 2023-02-06 19:15 UTC
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```v4.0.2@4df99e0df5a4adf2b92e7c6fc663de8fd4b9c325```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```Error```
**Code:** ```0```
**Message:** ```Call to undefined method Jikan\MyAnimeList\MalClient::getRecentReviews()```
**Trace:** ```/var/www/jikan-rest/app/Http/Controllers/V4DB/TopController.php on line 390```
**Request:** `GET /v4/top/reviews`

**Comment by pushrbx** [comment] 2023-02-06 19:52
Closing this as this is a duplicate of #344.

**Closed by pushrbx** 2023-02-06 19:52 UTC
Labels: duplicate
