### ISSUE TITLE
API error on http request

### ISSUE THREAD

**Issue by Tron247** [jikan-me/jikan-rest#357] opened 2023-03-27 22:58 UTC
I can't use the API currently, status:500 error: No suitable servers found

**Comment by baseplate-admin** [comment] 2023-03-28 02:15
Duplicate of #358 

Check https://discord.com/channels/460491088004907029/1090058467831722006

**Comment by irfan-dahir** [comment] 2023-03-28 05:19
Resolved

**Closed by irfan-dahir** 2023-03-28 05:19 UTC
