### ISSUE TITLE
Extra array push in OP/ED themes

### ISSUE THREAD

**Issue by Chortowod** [jikan-me/jikan-rest#135] opened 2020-09-04 22:34 UTC
https://api.jikan.moe/v3/anime/30
There is an extra array push in ending_themes:

> "ending_themes": [ 
    ...
    "\"Fly Me to the Moon (Rei",
    "Version)\" by Megumi Hayashibara (ep 5)",
    "\"Fly Me to the Moon (Rei",
    "Version)\" by Megumi Hayashibara (ep 6)",
    ...
]

when original lines look this:

> #02: "Fly Me to the Moon (Rei #5 Version)" by Megumi Hayashibara (ep 5)
#03: "Fly Me to the Moon (Rei #6 Version)" by Megumi Hayashibara (ep 6)

'#5' and '#6 ' turn into delimiter for a new array element I guess.

**Comment by irfan-dahir** [comment] 2020-09-05 07:35
Thanks for reporting this. That's indeed most likely what's happening.

Duplicate of https://github.com/jikan-me/jikan/issues/317 so I'll close this issue here. 
You may track the linked issue.

**Closed by irfan-dahir** 2020-09-05 07:35 UTC
